### ISSUE TITLE
pulseha does not like IPv6

### ISSUE THREAD

**Issue by akadata** [Syleron/PulseHA#106]
[root@pulse2 ~]# pulseha join -bind-addr=[2001:470:1f1d:174::2000]:9443 [2001:470:1f1d:174::1]:9443
PulseHA CLI connection error. Is the PulseHA service running?
rpc error: code = Unavailable desc = transport is closing

However you can manually add the [IPv6:Addr] as below and pulseha starts but nodes cant join with IPv6

  "pulse0.as.lab": {
            "bind_address": "[2001:470:1f1d:174::1]",
            "bind_port": "9443",
            "group_assignments": {
                "eth0": [
                    "group2"
                ]
            }
        }

https://godoc.org/golang.org/x/net/ipv6

**Comment by Syleron** [comment]
Should be resolved in the latest branch. Remember to add address/remove address/promote/demote a  node to ensure the IP comes up correctly and the other boxes on the network realize it.
