### ISSUE TITLE
cant add ipv6 floating ip

### ISSUE THREAD

**Issue by akadata** [Syleron/PulseHA#114]
[root@pulse0 ~]# cat /etc/pulseha/config.json 
{
    "pulse": {
        "tls": false
    },
    "floating_ip_groups": {
        "group1": []
    },
    "nodes": {
        "pulse0.as.lab": {
            "bind_address": "[2001:470:1f1d:174::50]",
            "bind_port": "9443",
            "group_assignments": {
                "eth0": [
                    "group1"
                ]
            }
        },
        "pulse1.as.lab": {
            "bind_address": "[2001:470:1f1d:174::60]",
            "bind_port": "9443",
            "group_assignments": {}
        },
        "pulse2.as.lab": {
            "bind_address": "[2001:470:1f1d:174::70]",
            "bind_port": "9443",
            "group_assignments": {}
        }
    },
    "logging": {
        "level": "info",
        "to_logfile": false,
        "logfile": "/var/log/pulseha.log"
    }
}[root@pulse0 ~]#pulseha groups -name=group1 -ips=2001:470:1f1d:174::100/64 add

[x] 2001:470:1f1d:174::100/64 already exists in group group1.. skipping.

[root@pulse0 ~]#pulseha groups -name=group1 -ips=2001:470:1f1d:174::100/64 add

[x] 2001:470:1f1d:174::100/64 already exists in group group1.. skipping.

[root@pulse0 ~]# pulseha groups -name=group1 -ips=[2001:470:1f1d:174::100/64] add

[x] invalid CDIR address specified

using [] causes the invalid CIDR

**Comment by Syleron** [comment]
issue resolved in latest dev build. Do not include brackets.
