### ISSUE TITLE
when enabling TLS the certificates are looked for in the wrong place. 

### ISSUE THREAD

**Issue by akadata** [Syleron/PulseHA#115]
**Jan 02 16:27:08 pulse0.as.lab pulse[6890]: [Jan  2 16:27:08][error] Could not load TLS cert: open ./certs/pulse1.as.lab.crt: no such file or directory**
Jan 02 16:27:08 pulse0.as.lab systemd[1]: pulseha.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1b8 pc=0x983ae2]
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: goroutine 15 [running]:
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: google.golang.org/grpc.(*ClientConn).GetState(0x0, 0xf259c0)
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: /root/go/src/google.golang.org/grpc/clientconn.go:648 +0x22
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: main.(*Memberlist).monitorClientConns(0xc42012e6a0, 0xc420040101)
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: /root/go/src/github.com/Syleron/PulseHA/src/memberlist.go:289 +0x106
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: main.(*Memberlist).(main.monitorClientConns)-fm(0xc420012d80)
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: /root/go/src/github.com/Syleron/PulseHA/src/member.go:239 +0x2a
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: github.com/Syleron/PulseHA/src/utils.Scheduler(0xc420011ff0, 0x3b9aca00)
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: /root/go/src/github.com/Syleron/PulseHA/src/utils/utils.go:86 +0x9c
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: created by main.(*Member).makeActive
Jan 02 16:27:08 pulse0.as.lab pulse[6890]: /root/go/src/github.com/Syleron/PulseHA/src/member.go:239 +0x510
Jan 02 16:27:08 pulse0.as.lab systemd[1]: Unit pulseha.service entered failed state.
Jan 02 16:27:08 pulse0.as.lab systemd[1]: pulseha.service failed.

**Comment by Syleron** [comment]
resolved in latest dev branch
