### ISSUE TITLE
Moving IP group from one NIC to another results in IPs being up on both old and new NIC.

### ISSUE THREAD

**Issue by Flashtekuk** [Syleron/PulseHA#137]
Moving IP group from one NIC to another within the config file, and restarting the service results in IP addresses being up on both old and new NIC.

**Comment by Syleron** [comment]
@Flashtekuk I have made a fix in the latest version of the dev branch. Can you please test at let me know? Thanks.

**Comment by Flashtekuk** [comment]
Yep, seems to be happily working now, thanks :1st_place_medal:
