### ISSUE TITLE
Dependency issue prevents service start

### ISSUE THREAD

**Issue by Flashtekuk** [Syleron/PulseHA#138]
Looks like you need to resolve an issue where pulseha tries to start before networking is fully up... CentOS 7 based system.

**Comment by Flashtekuk** [comment]
Add;

`After=network.target
Require=network.target`

In the [Unit] section of pulseha.service to cause this to be executed after the network script.

**Comment by Syleron** [comment]
@Flashtekuk I've updated the service file in the latest version of dev if you could test and get back with me. Thanks!
