### ISSUE TITLE
IP not being brought up

### ISSUE THREAD

**Issue by matthewcooper** [Syleron/pulseha#168]
When adding an IP the IP is not brought up on the box. but the IP is brought up on restart of PulseHA

[PulseHA-Logs.txt](https://github.com/Syleron/pulseha/files/4545163/PulseHA-Logs.txt)

**Comment by matthewcooper** [comment]
To add to this the IP is not brought down on removing

**Comment by Syleron** [comment]
resolved with the implementation of netlink
