### ISSUE TITLE
run pulse manually and enabled tls but no cert created message

### ISSUE THREAD

**Issue by akadata** [Syleron/PulseHA#96]
Hi Andrew

Most likely something I am doing wrong, it does not create the server.pem and also there is no --help feature or command line interface other than pulseha

I think pulse should 

```bash
[root@pulse0 ~]# pulse --help

   ___       _                  _
  / _ \_   _| |___  ___  /\  /\/_\
 / /_)/ | | | / __|/ _ \/ /_/ //_\\
/ ___/| |_| | \__ \  __/ __  /  _  \  Version v0.0.1-192-g3c01b7f
\/     \__,_|_|___/\___\/ /_/\_/ \_/  Build   3c01b7f

[Dec  4 20:56:15][info] Loading configuration file
^C

[root@pulse0 ~]# pulse -help

   ___       _                  _
  / _ \_   _| |___  ___  /\  /\/_\
 / /_)/ | | | / __|/ _ \/ /_/ //_\\
/ ___/| |_| | \__ \  __/ __  /  _  \  Version v0.0.1-192-g3c01b7f
\/     \__,_|_|___/\___\/ /_/\_/ \_/  Build   3c01b7f

[Dec  4 20:56:29][info] Loading configuration file
^C
[root@pulse0 ~]# 

```
Provide some help if it goes wrong

My JSON 

``json
{
    "pulse": {
        "tls": true
    },
    "floating_ip_groups": {},
    "nodes": {},
    "logging": {
        "level": "warning",
        "to_logfile": true,
        "logfile": "/var/log/pulseha.log"
    }
}
```

**Comment by Syleron** [comment]
You need to explain the situation a little more. Did you look inside of the etc/pulseha/ directory for your certs? if so, try deleting the certs directory and restart the pulse service. This should generate new keys for you.
